In [1]:
import re
def sorted_alphanumeric(data):
    convert = lambda text: int(text) if text.isdigit() else text.lower()
    alphanum_key = lambda key: [ convert(c) for c in re.split('([0-9]+)', key) ] 
    return sorted(data, key=alphanum_key)

In [19]:
import torch
import numpy as np
from os import listdir
from os.path import isfile, join

In [3]:
all_filenames = [f for f in listdir("../examples/embeddings") if isfile(join("../examples/embeddings", f))]

In [6]:
#all_filenames

['embedding_view_7.npy',
 'embedding_view_5.npy',
 'embedding_view_10.npy',
 'embedding_view_1.npy',
 'embedding_view_9.npy',
 'embedding_view_4.npy',
 'embedding_view_6.npy',
 'embedding_view_2.npy',
 'embedding_view_8.npy',
 'embedding_view_3.npy',
 'embedding_view_0.npy']

In [6]:
sorted_alphanumeric(all_filenames)[-3:]

['embedding_view_198.npy', 'embedding_view_199.npy', 'embedding_view_200.npy']

In [20]:
temp = []
for i in sorted_alphanumeric(all_filenames)[-2:]:
    print(i)
    file = "../examples/embeddings/"+ str(i)
    X= np.load(file)
    print (X)
    print (len(X))
    temp.append(X)

embedding_view_199.npy
[[ 0.0004937  -0.04685969  0.03279225 ...  0.01131871  0.01925463
   0.01817499]
 [-0.01582911 -0.00374661  0.04936786 ...  0.04891482 -0.01439126
   0.04827209]
 [-0.00562402 -0.03607745  0.05482373 ...  0.02067257 -0.02452708
   0.02684915]
 ...
 [ 0.03737227 -0.13092054  0.03512982 ... -0.0137063  -0.01196699
   0.00107233]
 [ 0.01025032 -0.11865969  0.0839469  ...  0.01657699  0.04801618
   0.05516839]
 [-0.02978084 -0.01684618 -0.01955128 ...  0.03976686 -0.00155486
   0.041101  ]]
987
embedding_view_200.npy
[[-0.00503975  0.00779563 -0.00050134 ...  0.00391093 -0.00622886
   0.00643654]
 [-0.03196756 -0.03291153  0.10989529 ...  0.10686878 -0.0353545
  -0.01885599]
 [-0.00413375 -0.02253784  0.01359259 ...  0.04477337 -0.00286504
   0.03105721]
 ...
 [-0.00695578  0.02515894 -0.00272731 ...  0.00822091 -0.00648033
  -0.02123139]
 [ 0.03656753 -0.04913883  0.01457653 ... -0.01058404 -0.01335351
  -0.09504897]
 [-0.02759236  0.04461268 -0.03530677 ... -0.0060

In [22]:
temp

[array([[ 0.0004937 , -0.04685969,  0.03279225, ...,  0.01131871,
          0.01925463,  0.01817499],
        [-0.01582911, -0.00374661,  0.04936786, ...,  0.04891482,
         -0.01439126,  0.04827209],
        [-0.00562402, -0.03607745,  0.05482373, ...,  0.02067257,
         -0.02452708,  0.02684915],
        ...,
        [ 0.03737227, -0.13092054,  0.03512982, ..., -0.0137063 ,
         -0.01196699,  0.00107233],
        [ 0.01025032, -0.11865969,  0.0839469 , ...,  0.01657699,
          0.04801618,  0.05516839],
        [-0.02978084, -0.01684618, -0.01955128, ...,  0.03976686,
         -0.00155486,  0.041101  ]], dtype=float32),
 array([[-0.00503975,  0.00779563, -0.00050134, ...,  0.00391093,
         -0.00622886,  0.00643654],
        [-0.03196756, -0.03291153,  0.10989529, ...,  0.10686878,
         -0.0353545 , -0.01885599],
        [-0.00413375, -0.02253784,  0.01359259, ...,  0.04477337,
         -0.00286504,  0.03105721],
        ...,
        [-0.00695578,  0.02515894, -0.0

In [23]:
emb = np.vstack(temp)

In [26]:
emb

array([[ 0.0004937 , -0.04685969,  0.03279225, ...,  0.01131871,
         0.01925463,  0.01817499],
       [-0.01582911, -0.00374661,  0.04936786, ...,  0.04891482,
        -0.01439126,  0.04827209],
       [-0.00562402, -0.03607745,  0.05482373, ...,  0.02067257,
        -0.02452708,  0.02684915],
       ...,
       [-0.00695578,  0.02515894, -0.00272731, ...,  0.00822091,
        -0.00648033, -0.02123139],
       [ 0.03656753, -0.04913883,  0.01457653, ..., -0.01058404,
        -0.01335351, -0.09504897],
       [-0.02759236,  0.04461268, -0.03530677, ..., -0.00605892,
        -0.05272878, -0.07473776]], dtype=float32)

In [27]:
len(emb)

1233

In [30]:
np.savez("../examples/final_embedding/final_embedding.npz", emb)

In [31]:
b = np.load('../examples/final_embedding/final_embedding.npz')

In [34]:
b['arr_0']

array([[ 0.0004937 , -0.04685969,  0.03279225, ...,  0.01131871,
         0.01925463,  0.01817499],
       [-0.01582911, -0.00374661,  0.04936786, ...,  0.04891482,
        -0.01439126,  0.04827209],
       [-0.00562402, -0.03607745,  0.05482373, ...,  0.02067257,
        -0.02452708,  0.02684915],
       ...,
       [-0.00695578,  0.02515894, -0.00272731, ...,  0.00822091,
        -0.00648033, -0.02123139],
       [ 0.03656753, -0.04913883,  0.01457653, ..., -0.01058404,
        -0.01335351, -0.09504897],
       [-0.02759236,  0.04461268, -0.03530677, ..., -0.00605892,
        -0.05272878, -0.07473776]], dtype=float32)

In [123]:
if my_file.is_file():
    print ("file is here")
    all_filenames = [f for f in listdir("../examples/embeddings") if isfile(join("../examples/embeddings", f))]
    print (all_filenames)
    all_filenames.sort()
    print (all_filenames)
    latest_file = all_filenames[-1]
    print(str(int(latest_file.split(".")[0].split("_")[2])+1))
    file = "../examples/embeddings/embedding_view_"+ str(int(latest_file.split(".")[0].split("_")[2])+1)+".npy"
else:
    file = '../examples/embeddings/embedding_view_0.npy'
f = open(file, 'wb')

file is here
['embedding_view_7.npy', 'embedding_view_5.npy', 'embedding_view_10.npy', 'embedding_view_1.npy', 'embedding_view_9.npy', 'embedding_view_4.npy', 'embedding_view_6.npy', 'embedding_view_2.npy', 'embedding_view_8.npy', 'embedding_view_3.npy', 'embedding_view_0.npy']
['embedding_view_0.npy', 'embedding_view_1.npy', 'embedding_view_10.npy', 'embedding_view_2.npy', 'embedding_view_3.npy', 'embedding_view_4.npy', 'embedding_view_5.npy', 'embedding_view_6.npy', 'embedding_view_7.npy', 'embedding_view_8.npy', 'embedding_view_9.npy']
10
